default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(scheme: "TooriApp")
  end

  desc "Build and upload beta"
  lane :beta do
    build_app(scheme: "TooriApp")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :android do
  desc "Assemble debug build"
  lane :beta do
    gradle(task: "assembleDebug")
  end
end
